-- Généré automatiquement à partir du Google Sheets de planification (2026-2027).
-- Vérifie les entrées marquées AMBIGU avant d'exécuter, puis lance ce fichier
-- APRÈS schema.sql dans Supabase SQL Editor.

-- ============ Horaire (schedule_events) ============
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-16', '18:00', 'practice', 'Pratique + Intra 18h-20h Simoneau');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-17', '18:00', 'practice', 'Pratique + Intra 18h-20h Simoneau');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-18', '18:00', 'other', 'Match intra-Équipe - 18h-20h Simoneau');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-19', '18:00', 'game', 'HC vs SSF - 18h00-20h Simoneau');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-20', '18:00', 'game', 'HC vs Albatros - 18h-20h Simoneau');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-21', '18:00', 'game', 'HC @ SSF 18h-20h');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-22', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-23', null, 'game', 'HC vs SSF (Heure + Aréna à Déterminer)');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-24', null, 'other', 'PÉDAGO');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-25', '18:15', 'other', 'Essayage M17 18h15-19h15');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-26', '13:10', 'other', '13h10 - 14h20 : M17 AAA');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-29', '16:30', 'other', 'M17 AAA : Marc-Simoneau 1 – 16h30-18h30');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-08-30', '15:30', 'other', 'M17 AAA : 15h30 Saguenay');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-05', null, 'other', 'Fête du travail');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-06', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-07', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-12', '19:00', 'game', 'M17 AAA vs COR - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-13', '16:00', 'game', 'M17 AAA vs TR - 16h00 - PGL');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-18', null, 'other', 'PÉDAGO');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-09-26', '19:00', 'game', 'M17 AAA vs Albatros - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-03', '19:00', 'game', 'M17 AAA vs Beauce - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-05', null, 'other', 'PÉDAGO');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-10', '17:30', 'game', 'M17 AAA vs Albatros - 17h30');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-11', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-12', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-17', null, 'game', 'M17 AAA vs SSF à déterminer');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-10-31', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-11-05', null, 'other', 'Challenge M17 AAA St-Augustin');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-11-14', '19:00', 'game', 'M17 AAA vs Beauce - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-11-15', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-11-21', '19:00', 'game', 'M17 AAA vs SAG - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-11-28', '19:00', 'game', 'M17 AAA vs Cascades - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-12-05', null, 'game', 'M17 AAA @ SAG');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-12-12', null, 'game', 'M17 AAA @ Beauce');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-12-13', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-12-21', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2026-12-28', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-01-04', null, 'other', 'PÉDAGO');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-01-16', '19:00', 'game', 'M17 AAA vs SSF - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-01-17', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-01-30', null, 'game', 'M17 AAA @ Albatros');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-02-04', null, 'other', 'Challenge M17 AAA St-Jérôme + Tournoi M13 AAA Pointes-aux-Trembles');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-02-13', '15:30', 'game', 'M17 AAA vs SAG - 15h30 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-02-14', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-02-27', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-01', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-08', null, 'other', 'PÉDAGO');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-13', '19:00', 'game', 'M17 AAA vs TR - 19h00 - MS2');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-14', null, 'game', 'M17 AAA @ SSF');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-20', null, 'game', 'M17 AAA @ Albatros');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-03-29', null, 'other', 'CONGÉ');
insert into schedule_events (event_date, start_time, event_type, title) values ('2027-04-18', null, 'game', 'M17 AAA @ SSF');

-- ============ Matchs (games) ============
insert into games (game_date, opponent, is_home, location) values ('2026-08-19', 'SSF', true, null);
insert into games (game_date, opponent, is_home, location) values ('2026-08-20', 'Albatros', true, null);
insert into games (game_date, opponent, is_home, location) values ('2026-08-21', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-08-23', 'SSF', true, null);
insert into games (game_date, opponent, is_home, location) values ('2026-09-06', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-09-12', 'COR', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-09-13', 'TR', true, 'PGL');
insert into games (game_date, opponent, is_home, location) values ('2026-09-26', 'Albatros', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-10-03', 'Beauce', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-10-10', 'Albatros', true, null);
insert into games (game_date, opponent, is_home, location) values ('2026-10-11', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-10-17', 'SSF à déterminer', true, null);
insert into games (game_date, opponent, is_home, location) values ('2026-10-31', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-11-14', 'Beauce', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-11-15', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-11-21', 'SAG', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-11-28', 'Cascades', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2026-12-05', 'SAG', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-12-12', 'Beauce', false, null);
insert into games (game_date, opponent, is_home, location) values ('2026-12-13', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-01-16', 'SSF', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2027-01-17', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-01-30', 'Albatros', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-02-13', 'SAG', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2027-02-14', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-02-27', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-03-13', 'TR', true, 'MS2');
insert into games (game_date, opponent, is_home, location) values ('2027-03-14', 'SSF', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-03-20', 'Albatros', false, null);
insert into games (game_date, opponent, is_home, location) values ('2027-04-18', 'SSF', false, null);
